export default
[ { sessionTitle: 'State of Vuenation',
    sessionAbstract: 'Creator of Vue, Evan You, will open the conference with an update on all thing Vue.js',
    twitter: 'https://twitter.com/youyuxi',
    name: 'Evan You',
    title: 'Creator of Vue.js ',
    img: 'https://cfp.connectevents.io/system/avatars/1107/large/499550.jpeg?1515104079' },
    { sessionTitle: 'The Future of Animation in Vue',
        sessionAbstract: 'Take animation to the next level, including use of soon-to-be-released browser features and upcoming changes to transitions and animation in Vue 3!',
        twitter: 'https://twitter.com/@sarah_edo',
        name: 'Sarah Drasner',
        title: 'Sarah Drasner is an award-winning Speaker, Senior Developer Advocate at Microsoft, and Staff Writer at CSS-Tricks. Sarah is also the co-founder of Web Animation Workshops, with Val Head. She’s the author of SVG Animations from O’Reilly and has given Frontend Masters workshops on Vue.js and Advanced SVG Animations. Sarah is formerly Manager of UX Design & Engineering at Trulia (Zillow).',
        img: 'https://cfp.connectevents.io/system/avatars/1151/large/97cssCek_400x400.jpg?1513436066' },
    { sessionTitle: 'How do you Vue?',
        sessionAbstract: 'Vue core team member Chris Fritz will dive into practical tips n\' tricks for developing great Vue applications!',
        twitter: 'https://twitter.com/chrisvfritz',
        name: 'Chris Fritz',
        title: 'Educator/hacker working to make web dev simpler. Vue core team member and curator of our docs.',
        img: 'https://cfp.connectevents.io/system/avatars/978/large/rMSXLIWW_400x400.jpg?1515104982' },
    { sessionTitle: '5 Brain Science Hacks to Successfully Level up in Programming',
        sessionAbstract: 'Leveling up in programming can be downright infuriating, time consuming & expensive. Take the frustration out of the equation with these 5 hacks based on research in educational psychology (brain science) applied to coding. Save money, time, and aggravation while expanding your knowledge base.\r\n\r\n',
        twitter: 'https://twitter.com/fwallacephd',
        name: 'Dr. Faith H. Wallace',
        title: 'Web Developer. Professor. Writer. Hogwarts Student. Doctor Who Companion. Okay, so maybe I am not a student at Hogwarts… I am sure I\'d be sorted into Ravenclaw! And, maybe I am not a Doctor Who companion… But wouldn’t time traveling in the TARDIS be amazing? I am a former college professor turned web developer with the goal of making teaching and learning code more accessible.',
        img: 'https://cfp.connectevents.io/system/avatars/1198/large/faith.jpg?1543892160' },
    { sessionTitle: 'Ionic & Vue for fast mobile apps',
        sessionAbstract: 'Vue as a framework prides itself for providing an excellent developer experience out of the box so devs can build awesome apps with it. Ionic as a component library shares these same values while providing a great UI for any kind of app. In this talk, we\'ll look at how we can use Ionic and Vue together to quickly create a compelling mobile application that can be deployed to the iOS, Android, and the Web.',
        twitter: 'https://twitter.com/mhartington',
        name: 'Mike Hartington',
        title: 'Mike is a Developer on the Ionic Framework team, as well as a GDE in Angular, Web Technologies, and Firebase. Aside from technologies, Mike loves a good beer and building cool things.',
        img: 'https://cfp.connectevents.io/system/avatars/439/large/mike-headshot-14.png?1481752576' },
    { sessionTitle: 'Vuex Explained Visually',
        sessionAbstract: 'Understand Vue\'s state management pattern through a visual walkthrough.',
        twitter: 'https://twitter.com/adamjahr',
        name: 'Adam Jahr',
        title: 'Adam Jahr is co-founder and instructor over at VueMastery.com, where he releases weekly Vue.js video tutorials and articles. He also hosts the Official Vue News podcast, covering the latest news and libraries in the Vue.js ecosystem. ',
        img: 'https://cfp.connectevents.io/system/avatars/1685/large/adam.jpg?1543880130' },
    { sessionTitle: 'Advanced animations with Vue.js',
        sessionAbstract: 'In this talk, I’ll walk you through the coolest features of Vue.js and explore how to combine them with advanced CSS animations and transitions in order to create fancy interactive animations. We\'ll dive into a game built with Vue.js and how to apply similar techniques to spice up real-world applications.',
        twitter: 'https://twitter.com/@krystalcampioni',
        name: 'Krystal Campioni',
        title: 'Senior Front-end Developer @Shopify. Giphy and Whale fluent speaker. Tech, design, and ufology enthusiast.',
        img: 'https://cfp.connectevents.io/system/avatars/1686/large/krystal.jpeg?1540114595' },
    { sessionTitle: 'Building desktop applications with Vue',
        sessionAbstract: 'With Vue your experience is not limited to web or mobile application - you can create a desktop app as well! Let\'s do it together during this talk',
        twitter: 'https://twitter.com/@n_tepluhina',
        name: 'Natalia Tepluhina',
        title: 'Frontend Developer with a passion to VueJS. Vue Vixens CTO',
        img: 'https://cfp.connectevents.io/system/avatars/1237/large/natalia.jpg?1529377889' },
    { sessionTitle: '9 performance secrets revealed',
        sessionAbstract: 'With these 9 secrets revealed to you, take the performance of your app to the next level and make your users happy!',
        twitter: 'https://twitter.com/akryum',
        name: 'Guillaume Chau',
        title: 'Vue Core member, Open Source contributor in the Vue, Meteor and Apollo GraphQL communities',
        img: 'https://cfp.connectevents.io/system/avatars/988/large/avatar.jpg?1529570442' },
    { sessionTitle: 'Phenomenal Design Patterns In Vue',
        sessionAbstract: 'Jacob provides a high level overview of common features that can be solved with time tested design patterns from the Gang of Four and mixed with Vue with Vuex to solve common problems like:\r\nThe Memento for undo and redo\r\nThe Bridge for an awesome drawing API\r\nThe Decorator for making games with\r\nThe Builder for your fast food ordering system\r\nAnd many more.\r\nThe best part is you\'ll still use Vuex to manage your global state and Vue to manage your reactivity, but also add in some sweet design patterns to quickly solve tougher common programming problems.\r\nIt\'s not always easy to figure out where these classic design patterns fit in a modern framework like Vue which has solved many specific problems already, but Jacob will show you how they fit in perfectly',
        twitter: 'https://twitter.com/jakecodes',
        name: 'Jacob Schatz',
        title: 'Jacob Schatz started the frontend team at GitLab. He quickly realized  the endless possibilities at GitLab. Jacob\'s code has reached millions of people, from making sites for Panera Bread, CVS, Weight Watchers and of course, GitLab, to his person fun projects like MyCaseBuilder. He has been programming since 2006, and has a degree in piano performance. He has also published 2 books, and tons of tutorials and courses.',
        img: 'https://cfp.connectevents.io/system/avatars/1016/large/jacobschatz.jpg?1510619506' },
    { sessionTitle: 'Demystifying: the dark art of SFC compilation',
        sessionAbstract: 'Vue single file components empowers developers with ability to write declarative render functions using plain HTML-like syntax. The so called SFCs also provide features like collocation and scoped styles. We tend to use these SFCs effortlessly as any other JavaScript file but to reach that level of ease, Vue does the heavy lifting of transpilation. This talk takes a deep dive in the compilation process of Vue components and explains how to write a custom block processor. It also discovers some less known facts about SFCs.',
        twitter: 'https://twitter.com/znck0',
        name: 'Rahul Kadyan',
        title: '',
        img: 'https://cfp.connectevents.io/system/avatars/983/large/me.jpg?1522970914' },
    { sessionTitle: 'Building fast and semantic input masks in VueJS',
        sessionAbstract: 'Input masking is a common pattern in form design that guide users to enter information in the correct format in a consistent manner. Typically this involves formatting user input according to the type of data they represent like dates, phone numbers, addresses and credit card numbers. You can achieve an input mask in Vue by leaning heavily Vue’s reactivity system chiefly methods, computed, and watchers. In this talk, we will cover the distinction between the various components that make up Vue’s reactivity system and how to leverage it in order to create semantic and robust input elements that respond seamlessly to user feedback.',
        twitter: 'https://twitter.com/shortdiv',
        name: 'Divya Sasidharan',
        title: '',
        img: 'https://cfp.connectevents.io/system/avatars/1122/large/divya.jpg?1543880162' },
    { sessionTitle: 'Back to the Vueture: Stuck in the Event Loop with a Trash Brain',
        sessionAbstract: 'Do you feel like you\'re stuck in the event loop of hell, forced to fumble through setTimeout after setTimeout day after day when all you want to do is leap out of bed singing "I got Vue babe" and wielding nextTick in style? Join us as we dive into the source code of nextTick and microtasks and make nextTick work for you today!',
        twitter: 'https://twitter.com/@halftes6',
        name: 'tessa',
        title: 'Tessa is an artist and software engineer whose idea of a good time includes creating UI components and comic book layouts and watching movies with her guinea pig.',
        img: 'https://cfp.connectevents.io/system/avatars/1749/large/tessa.jpg?1542662000' },
    { sessionTitle: 'Web Accessibility with VueJS',
        sessionAbstract: 'Want to learn about Web Accessibility with Vue.js? A Board Certified Assistant Behavior Analyst turned Web Developer gives you a different take on accessibility and why it is important. Web Accessibility is a way to make everyone - regardless of hardware, software, language, location, or ability - have access to the web and internet in whole. Let\'s use Vue.js to create accessible web apps!',
        twitter: '',
        name: 'Maria Lamardo',
        title: 'My name is Maria Lamardo. I am originally from Caracas, Venezuela and currently reside in North Carolina. I graduated cum laude from Florida International University where I received a Bachelor’s in Psychology and a minor in business. I provided behavioral therapy for children with developmental disabilities for 8 years as a Board Certified Assistant Behavior Analyst. Now, as a software developer, I am very passionate about the importance of web accessibility.',
        img: 'https://cfp.connectevents.io/system/avatars/1699/large/maria.jpeg?1543892057' },
    { sessionTitle: 'Dynamic CSS with Vue',
        sessionAbstract: 'CSS has come a long way since the browser wars of the late 90s. What used to be a struggle, is now often a breeze (see box-shadow or border-radius). But the last 2 years have pushed CSS into entirely new territory: with DOM-aware variables and calculations that can drive your design.\r\n\r\nWe can inject data directly into our themes and layouts, but where does that data come from, and how do we safely wire it up? Vue provides all the tools we need, but first we have to understand the possibilities and constraints. We\'ll cover…\r\n\r\nThe basics for understanding CSS custom properties, grid, and calc().\r\nPractical examples and use-cases for data-infused design.\r\nHow dynamic CSS & JS work together in this new paradigm.\r\nRobust patterns for managing themes, layouts, and more from Vue.',
        twitter: 'https://twitter.com/mirisuzanne',
        name: 'Miriam E Suzanne',
        title: 'Miriam is an author, performer, musician, designer, and web developer — working with OddBird, Teacup Gorilla, Grapefruit Lab, and CSS Tricks. She’s the author of Riding SideSaddle* and The Post-Obsolete Book, co-author of Jump Start Sass (Sitepoint), and creator of the Susy and True open source tools.',
        img: 'https://cfp.connectevents.io/system/avatars/1142/large/miriam.jpg?1543891975' },
    { sessionTitle: 'Getting started with Nuxt.js ',
        sessionAbstract: 'So you know the Vue basics but keep on hearing about this Nuxt.js framework.  Perhaps you’re wondering if you should use it on your next project?  In this talk Gregg Pollack will visually explain why you should care about Nuxt and cover all the basics of using the framework to create scalable Vue applications.  By the end you’ll see why Gregg describes Nuxt.js as: production ready Vue which helps you employ best practices as you build.',
        twitter: 'https://twitter.com/greggpollack',
        name: 'Gregg Pollack',
        title: 'Gregg Pollack is the founder of Vue Mastery, the ultimate learning resource for Vue Developers.  Previously he founded Code School, an online software programming school which was acquired by Pluralsight, Envy, a web application development firm, and Starter Studio, Orlando\'s first technical accelerator now in its eighth class.  He’s passionate about being a father, teaching programming, traveling the world, organizational psychology, and attending theater.',
        img: 'https://cfp.connectevents.io/system/avatars/1059/large/GreggPollack-Square-New.jpg?1513615639' } ]
